In [1]:
import numpy as np
import pandas as pd
import warnings
import graphviz
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import seaborn as sns

from sklearn import datasets
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, export_graphviz
from sklearn.model_selection import  train_test_split

In [2]:
df = pd.read_csv("mean_df")

In [3]:
df

,ПОЛ в плазме,ПОЛ в мембр. Эритроцитов,Лактат,Глюкоза,Общий белок,Мочевина,Кортизол,Зонулин,Холестерин,здоров(1)\болен(0),...,ЭХ_x,ТГ_y,НеЖК,ХЛ,ФЛ_y,ФЛ,СХ_y,СЖК,ТГ,ЭХ_y
0,3.08,33.333333,29.622619,6.827381,39.155,7.063651,248.718361,95.402933,2.504494,0.0,...,14.92,16.94,27.66,15.87,24.61,11.100000,17.510000,27.650000,22.610000,21.140000
1,2.05,28.205128,29.622619,6.827381,39.155,7.063651,248.718361,95.402933,2.504494,0.0,...,16.57,15.78,20.72,12.09,34.84,14.740000,16.960000,21.820000,25.220000,21.260000
2,1.03,23.076923,8.000000,8.700000,65.000,7.700000,369.000000,0.283000,3.000000,0.0,...,22.08,21.59,19.26,14.86,22.21,8.670000,13.460000,19.590000,33.530000,24.760000
3,1.53,38.461538,6.800000,6.000000,85.600,7.700000,328.900000,0.370714,3.000000,0.0,...,19.31,24.98,34.26,7.48,13.97,15.560000,19.880000,29.380000,28.710000,24.360000
4,2.05,30.769231,6.800000,6.000000,85.600,7.700000,328.900000,0.370714,3.000000,0.0,...,20.15,19.35,32.04,16.17,12.29,8.100000,19.400000,15.900000,30.890000,25.730000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,1.53,25.641026,9.600000,9.300000,75.200,10.900000,222.420000,0.342000,3.800000,0.0,...,15.70,26.81,36.40,14.52,6.57,11.380000,15.270000,23.910000,19.650000,29.790000
91,1.53,33.333333,10.000000,6.000000,65.000,8.900000,467.940000,0.256000,7.300000,0.0,...,19.63,24.78,29.94,11.44,14.21,20.270000,32.100000,22.880000,14.060000,10.690000
92,1.03,33.333333,10.000000,6.000000,65.000,8.900000,467.940000,0.256000,7.300000,0.0,...,25.13,19.71,35.98,11.39,7.79,12.140000,16.930000,23.380000,27.550000,19.100000
93,1.03,35.897436,29.622619,6.827381,39.155,7.063651,248.718361,95.402933,2.504494,0.0,...,15.70,26.81,36.40,14.52,6.58,11.650000,18.140000,26.300000,22.310000,21.600000
94,1.53,33.333333,5.200000,8.000000,41.500,8.900000,373.440000,0.297000,2.600000,0.0,...,18.20,21.98,33.04,15.82,10.96,11.925735,19.081912,22.808235,24.416029,24.114265

In [4]:
df.info()
df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ПОЛ в плазме              95 non-null     float64
 1   ПОЛ в мембр. Эритроцитов  95 non-null     float64
 2   Лактат                    95 non-null     float64
 3   Глюкоза                   95 non-null     float64
 4   Общий белок               95 non-null     float64
 5   Мочевина                  95 non-null     float64
 6   Кортизол                  95 non-null     float64
 7   Зонулин                   95 non-null     float64
 8   Холестерин                95 non-null     float64
 9   здоров(1)\болен(0)        95 non-null     float64
 10  ЭХС                       95 non-null     float64
 11  ТГ_x                      95 non-null     float64
 12  НЭЖК                      95 non-null     float64
 13  СХ_x                      95 non-null     float64
 14  ФЛ_x                      95 non-null     float64
 15  Пол                       95 non-null     float64
 16  Возраст                   95 non-null     float64
 17  Форма                     95 non-null     float64
 18  ЭХ_x                      95 non-null     float64
 19  ТГ_y                      95 non-null     float64
 20  НеЖК                      95 non-null     float64
 21  ХЛ                        95 non-null     float64
 22  ФЛ_y                      95 non-null     float64
 23  ФЛ                        95 non-null     float64
 24  СХ_y                      95 non-null     float64
 25  СЖК                       95 non-null     float64
 26  ТГ                        95 non-null     float64
 27  ЭХ_y                      95 non-null     float64
dtypes: float64(28)
memory usage: 20.9 KB

,ПОЛ в плазме,ПОЛ в мембр. Эритроцитов,Лактат,Глюкоза,Общий белок,Мочевина,Кортизол,Зонулин,Холестерин,здоров(1)\болен(0),...,ЭХ_x,ТГ_y,НеЖК,ХЛ,ФЛ_y,ФЛ,СХ_y,СЖК,ТГ,ЭХ_y
0,3.08,33.333333,29.622619,6.827381,39.155,7.063651,248.718361,95.402933,2.504494,0.0,...,14.92,16.94,27.66,15.87,24.61,11.10,17.51,27.65,22.61,21.14
1,2.05,28.205128,29.622619,6.827381,39.155,7.063651,248.718361,95.402933,2.504494,0.0,...,16.57,15.78,20.72,12.09,34.84,14.74,16.96,21.82,25.22,21.26
2,1.03,23.076923,8.000000,8.700000,65.000,7.700000,369.000000,0.283000,3.000000,0.0,...,22.08,21.59,19.26,14.86,22.21,8.67,13.46,19.59,33.53,24.76
3,1.53,38.461538,6.800000,6.000000,85.600,7.700000,328.900000,0.370714,3.000000,0.0,...,19.31,24.98,34.26,7.48,13.97,15.56,19.88,29.38,28.71,24.36
4,2.05,30.769231,6.800000,6.000000,85.600,7.700000,328.900000,0.370714,3.000000,0.0,...,20.15,19.35,32.04,16.17,12.29,8.10,19.40,15.90,30.89,25.73

In [5]:
x = df.drop("здоров(1)\болен(0)",axis=1)
y = df["здоров(1)\болен(0)"]

In [6]:
# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify=y)

In [7]:
x_train

,ПОЛ в плазме,ПОЛ в мембр. Эритроцитов,Лактат,Глюкоза,Общий белок,Мочевина,Кортизол,Зонулин,Холестерин,ЭХС,...,ЭХ_x,ТГ_y,НеЖК,ХЛ,ФЛ_y,ФЛ,СХ_y,СЖК,ТГ,ЭХ_y
11,2.05,30.769231,6.8,6.0,47.00,7.70,314.510000,0.217000,5.000,22.0,...,19.38,25.68,30.69,12.71,11.54,24.350000,27.090000,24.520000,12.190000,11.850000
50,6.40,10.700000,52.0,11.5,5.50,2.05,30.769231,300.000000,0.175,9.0,...,19.38,21.19,30.56,16.48,12.39,5.900000,15.000000,22.300000,27.600000,29.100000
39,1.03,28.205128,6.0,1.7,63.00,7.70,184.540000,0.411000,3.800,22.0,...,16.93,24.28,37.98,12.32,8.49,11.900000,17.350000,26.120000,22.820000,21.810000
8,1.53,35.897436,8.4,5.6,41.50,8.90,638.600000,0.322000,4.600,15.0,...,15.16,21.94,34.23,13.59,15.10,11.060000,21.050000,17.610000,26.220000,24.060000
5,1.03,25.641026,5.2,6.0,44.10,10.90,235.230000,0.622000,4.400,16.0,...,15.47,20.05,39.73,13.42,11.33,9.900000,20.260000,18.500000,26.430000,24.910000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,1.03,25.641026,5.2,6.0,44.10,10.90,235.230000,0.622000,4.400,19.0,...,11.44,22.15,41.55,15.75,9.11,8.100000,19.400000,15.900000,30.890000,25.730000
15,2.05,28.205128,7.6,8.0,41.50,15.26,361.280000,0.370714,4.900,18.0,...,18.50,22.14,40.32,9.92,9.12,10.380000,23.160000,15.530000,21.320000,29.610000
29,1.53,25.641026,6.8,9.3,60.00,14.70,301.800000,0.289000,2.000,16.0,...,17.85,24.65,31.54,15.14,10.82,13.610000,19.060000,21.970000,22.710000,22.660000
31,9.60,4.600000,52.0,5.6,6.26,4.10,25.641026,210.000000,0.194,16.0,...,13.76,24.52,37.78,15.76,8.18,11.925735,19.081912,22.808235,24.416029,24.114265
4,2.05,30.769231,6.8,6.0,85.60,7.70,328.900000,0.370714,3.000,16.0,...,20.15,19.35,32.04,16.17,12.29,8.100000,19.400000,15.900000,30.890000,25.730000

In [ ]:
clf = DecisionTreeClassifier(random_state = 42,class_weight= {0: 1, 1: 10},max_depth = 3)
clf.fit(x_train, y_train)

DecisionTreeClassifier(class_weight={0: 1, 1: 10}, max_depth=3, random_state=42)

In [16]:
prediction = clf.predict(x_test)
accuracy_score(prediction, y_test)

0.9655172413793104

In [10]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix, classification_report
)

In [11]:
print(f"Accuracy:{accuracy_score(y_test, prediction):.3f}")
print(f"Precision:{precision_score(y_test, prediction):.3f}")
print(f"Recall:  {recall_score(y_test, prediction):.3f}")
print(f"F1-score: {f1_score(y_test, prediction):.3f}")
# print(f"ROC-AUC:{roc_auc_score(y_test, y_proba):.3f}")
print("\nConfusion Matrix:\n", confusion_matrix(y_test, prediction))
print("\nClassification Report:\n", classification_report(y_test, prediction))

Accuracy:0.966
Precision:1.000
Recall:  0.800
F1-score: 0.889

Confusion Matrix:
 [[24  0]
 [ 1  4]]

Classification Report:
               precision    recall  f1-score   support

         0.0       0.96      1.00      0.98        24
         1.0       1.00      0.80      0.89         5

    accuracy                           0.97        29
   macro avg       0.98      0.90      0.93        29
weighted avg       0.97      0.97      0.96        29

In [12]:
from sklearn.model_selection import cross_val_score


scores_f1 = cross_val_score(clf, x, y, cv=5, scoring='f1')

print(f"F1-результаты по фолдам: {scores_f1}")
print(f"Средний F1: {scores_f1.mean():.2f}")

F1-результаты по фолдам: [0.8        0.8        0.8        0.85714286 0.8       ]
Средний F1: 0.81