In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
BP_OG = pd.read_excel("data_for_EEG/BP_OG.xlsx",sheet_name="Горизонтальная")
BP_ZG = pd.read_excel("data_for_EEG/BP_ZG.xlsx",sheet_name="Горизонтальная")
control_OG = pd.read_excel("data_for_EEG/Kontrol_OG.xlsx",sheet_name="Горизонтальная")
control_ZG = pd.read_excel("data_for_EEG/Kontorol_ZG.xlsx",sheet_name="Горизонтальная")

In [3]:
import pandas as pd
import os

# Список ваших файлов (только страницы "Горизонтальная")
BP_OG["здоров(1)/болен(0)"] = 0
BP_ZG["здоров(1)/болен(0)"] = 0
control_OG["здоров(1)/болен(0)"] = 1
control_ZG["здоров(1)/болен(0)"] = 1
files = [
BP_OG,
BP_ZG,
control_OG,
control_ZG
]

all_dfs = []

for file in files:
    # Загружаем CSV
    # df = pd.read_csv(file)
    df = file
        
    all_dfs.append(df)

# Объединяем все таблицы в одну
# Используем ignore_index=True, чтобы пересобрать индексы строк
final_df = pd.concat(all_dfs, ignore_index=True, sort=False)

# Сохраняем результат в Excel
final_df = final_df.drop("Имя",axis = 1)
final_df.to_csv("combined_horizontal_data.csv", index=False)

print("Файлы успешно объединены в 'combined_horizontal_data.xlsx'")

/tmp/ipykernel_34270/2193443751.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BP_OG["здоров(1)/болен(0)"] = 0
/tmp/ipykernel_34270/2193443751.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  BP_ZG["здоров(1)/болен(0)"] = 0
/tmp/ipykernel_34270/2193443751.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  control_OG["здоров(1)/болен(0)"] = 1
/tmp/ipykernel_34270/2193443751.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  control_ZG["здоров(1)/болен(0)"] = 1

Файлы успешно объединены в 'combined_horizontal_data.xlsx'

In [5]:
combined_horizontal_data = pd.read_csv("data_for_EEG/combined_horizontal_data.csv")
combined_horizontal_data

,D_1:2,D_1:3,D_1:4,D_1:5,D_1:6,D_1:7,D_1:8,D_1:9,D_1:10,D_1:11,...,B2_17:19,B2_17:20,B2_17:21,B2_18:19,B2_18:20,B2_18:21,B2_19:20,B2_19:21,B2_20:21,здоров(1)/болен(0)
0,0.943,0.949,0.958,0.916,0.892,0.863,0.672,0.837,0.729,0.666,...,0.590,0.810,0.798,0.524,0.568,0.599,0.652,0.578,0.888,0
1,0.658,0.637,0.800,0.882,0.908,0.671,0.688,0.593,0.706,0.635,...,0.535,0.895,0.884,0.504,0.869,0.869,0.543,0.563,0.971,0
2,0.785,0.724,0.643,0.733,0.690,0.756,0.596,0.669,0.676,0.699,...,0.554,0.758,0.711,0.499,0.546,0.573,0.649,0.587,0.747,0
3,0.690,0.698,0.758,0.839,0.829,0.667,0.649,0.629,0.656,0.577,...,0.680,0.901,0.920,0.734,0.875,0.930,0.718,0.754,0.948,0
4,0.796,0.683,0.838,0.845,0.766,0.746,0.605,0.705,0.700,0.681,...,0.514,0.746,0.662,0.531,0.635,0.626,0.570,0.567,0.898,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,0.844,0.852,0.872,0.942,0.953,0.817,0.697,0.651,0.793,0.709,...,0.589,0.861,0.824,0.516,0.615,0.641,0.615,0.522,0.766,1
182,0.902,0.902,0.715,0.808,0.782,0.726,0.734,0.575,0.623,0.662,...,0.632,0.779,0.644,0.618,0.803,0.744,0.714,0.623,0.914,1
183,0.856,0.718,0.690,0.896,0.838,0.659,0.739,0.646,0.668,0.671,...,0.602,0.835,0.830,0.608,0.674,0.614,0.548,0.496,0.865,1
184,0.943,0.933,0.849,0.842,0.870,0.696,0.693,0.668,0.695,0.674,...,0.668,0.811,0.743,0.508,0.575,0.643,0.731,0.595,0.825,1
185,0.848,0.849,0.841,0.957,0.929,0.809,0.649,0.755,0.816,0.754,...,0.505,0.780,0.827,0.498,0.710,0.800,0.619,0.506,0.787,1

In [6]:
import pandas as pd

# Разделяем на два класса
df_0 = combined_horizontal_data[combined_horizontal_data['здоров(1)/болен(0)'] == 0]
df_1 = combined_horizontal_data[combined_horizontal_data['здоров(1)/болен(0)'] == 1]

# Случайно выбираем из нулевого класса столько же строк, сколько в первом
df_0_downsampled = df_0.sample(n=len(df_1), random_state=42)

# Соединяем обратно
df_balanced = pd.concat([df_0_downsampled, df_1])

# Перемешиваем строки
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)
df_balanced.to_csv("df_balanced.csv", index=False)
df_balanced

,D_1:2,D_1:3,D_1:4,D_1:5,D_1:6,D_1:7,D_1:8,D_1:9,D_1:10,D_1:11,...,B2_17:19,B2_17:20,B2_17:21,B2_18:19,B2_18:20,B2_18:21,B2_19:20,B2_19:21,B2_20:21,здоров(1)/болен(0)
0,0.877,0.898,0.896,0.971,0.850,0.832,0.891,0.612,0.737,0.656,...,0.630,0.831,0.833,0.681,0.810,0.814,0.736,0.732,0.999,1
1,0.619,0.621,0.953,0.978,0.949,0.651,0.651,0.944,0.896,0.561,...,0.536,0.873,0.922,0.552,0.674,0.698,0.593,0.549,0.906,0
2,0.573,0.535,0.822,0.822,0.750,0.560,0.519,0.732,0.716,0.530,...,0.470,0.749,0.761,0.487,0.669,0.665,0.522,0.469,0.776,0
3,0.601,0.632,0.861,0.909,0.924,0.602,0.557,0.824,0.858,0.519,...,0.504,0.929,0.883,0.556,0.751,0.699,0.525,0.498,0.923,0
4,0.667,0.755,0.839,0.783,0.800,0.762,0.715,0.752,0.757,0.731,...,0.525,0.928,0.941,0.510,0.712,0.789,0.571,0.547,0.945,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,0.819,0.809,0.818,0.848,0.854,0.772,0.657,0.755,0.707,0.756,...,0.592,0.866,0.916,0.588,0.845,0.948,0.697,0.631,0.924,0
84,0.868,0.740,0.781,0.657,0.434,0.707,0.608,0.565,0.493,0.441,...,0.429,0.521,0.480,0.380,0.548,0.602,0.628,0.525,0.911,1
85,0.943,0.965,0.895,0.904,0.790,0.793,0.813,0.844,0.836,0.773,...,0.589,0.849,0.786,0.629,0.852,0.852,0.697,0.678,0.954,1
86,0.955,0.950,0.860,0.757,0.839,0.805,0.864,0.656,0.673,0.696,...,0.466,0.817,0.818,0.489,0.838,0.844,0.551,0.548,0.998,0
87,0.788,0.640,0.910,0.984,0.936,0.697,0.646,0.882,0.819,0.566,...,0.541,0.818,0.838,0.565,0.561,0.576,0.582,0.555,0.920,1

In [7]:
df_0_remaining = df_0.drop(df_0_downsampled.index)

# Сохраняем, если нужно
df_0_remaining.to_csv("data_for_EEG/df_leftovers.csv", index=False)