In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_all_name = pd.read_excel(r"tables.xlsx",sheet_name="ВСЕ ИМЕНА")
df_biochemistry = pd.read_excel(r"tables.xlsx",sheet_name="БИОХИМИЯ")
df_plasma = pd.read_excel(r"tables.xlsx",sheet_name="ФРАКЦИИ плазма")
df_red_blood_cells = pd.read_excel(r"tables.xlsx",sheet_name="ФРАКЦИИ эритр.")
df_sheet7 = pd.read_excel(r"tables.xlsx",sheet_name="Лист7")

In [3]:
df_all_name

             ФИО  Пол  Возраст         Форма  Стадия
0              1    ж     62.0     смешанная     3.0
1    Азиатцева 2    ж     70.0     смешанная     3.0
2    Азиатцева 3    ж     67.0     смешанная     3.0
3   Андриянова 4    ж     74.0     смешанная     3.0
4   Андриянова 5    ж     60.0  дрожательная     3.0
..           ...  ...      ...           ...     ...
90   Щербаков 91    ж      NaN           NaN     NaN
91     Юнусов 92    ж      NaN           NaN     NaN
92     Юнусов 93    ж      NaN           NaN     NaN
93      Янова 94    ж      NaN           NaN     NaN
94      Янова 95  NaN      NaN           NaN     NaN

[95 rows x 5 columns]

In [4]:
df_plasma

             ФИО     ЭХ     ТГ   НеЖК     ХЛ     ФЛ
0              1  14.92  16.94  27.66  15.87  24.61
1    Азиатцева 2  16.57  15.78  20.72  12.09  34.84
2    Азиатцева 3  22.08  21.59  19.26  14.86  22.21
3   Андриянова 4  19.31  24.98  34.26   7.48  13.97
4   Андриянова 5  20.15  19.35  32.04  16.17  12.29
..           ...    ...    ...    ...    ...    ...
91     Юнусов 92  19.63  24.78  29.94  11.44  14.21
92     Юнусов 93  25.13  19.71  35.98  11.39   7.79
93      Янова 94  15.70  26.81  36.40  14.52   6.58
94      Янова 95  18.20  21.98  33.04  15.82  10.96
95      Янова 57  19.29  23.20  39.38  10.79   7.34

[96 rows x 6 columns]

In [5]:



# df_red_blood_cells = pd.read_excel(r"XAXAXAXAXA_tablichechki.xlsx",sheet_name="ФРАКЦИИ эритр.")

In [6]:
df_B_sh = pd.merge(df_biochemistry, df_sheet7, how='outer', on="ФИО", left_on=None, right_on=None, left_index=False, right_index=False)

In [7]:
df_B_sh_all = pd.merge(df_B_sh, df_all_name, how='outer', on="ФИО", left_on=None, right_on=None, left_index=False, right_index=False)

In [8]:
df_B_sh_all_plasma = pd.merge(df_B_sh_all, df_plasma, how='outer', on="ФИО", left_on=None, right_on=None, left_index=False, right_index=False)

In [9]:
df_finaly = pd.merge(df_B_sh_all_plasma, df_red_blood_cells, how='outer', on="ФИО", left_on=None, right_on=None, left_index=False, right_index=False)

In [10]:
df_finaly

,№,ФИО,ПОЛ в плазме,ПОЛ в мембр. Эритроцитов,Лактат,Глюкоза,Общий белок,Мочевина,Кортизол,Зонулин,...,ЭХ_x,ТГ_y,НеЖК,ХЛ,ФЛ_y,ФЛ,СХ_y,СЖК,ТГ,ЭХ_y
0,1.0,1,3.08,33.333333,NaN,NaN,NaN,NaN,NaN,NaN,...,14.92,16.94,27.66,15.87,24.61,11.10,17.51,27.65,22.61,21.14
1,2.0,Азиатцева 2,2.05,28.205128,NaN,NaN,NaN,NaN,NaN,NaN,...,16.57,15.78,20.72,12.09,34.84,14.74,16.96,21.82,25.22,21.26
2,3.0,Азиатцева 3,1.03,23.076923,8.0,8.7,65.0,7.7,369.00,0.283000,...,22.08,21.59,19.26,14.86,22.21,8.67,13.46,19.59,33.53,24.76
3,4.0,Андриянова 4,1.53,38.461538,6.8,6.0,85.6,7.7,328.90,0.370714,...,19.31,24.98,34.26,7.48,13.97,15.56,19.88,29.38,28.71,24.36
4,5.0,Андриянова 5,2.05,30.769231,6.8,6.0,85.6,7.7,328.90,0.370714,...,20.15,19.35,32.04,16.17,12.29,8.10,19.40,15.90,30.89,25.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,92.0,Юнусов 92,1.53,33.333333,10.0,6.0,65.0,8.9,467.94,0.256000,...,19.63,24.78,29.94,11.44,14.21,20.27,32.10,22.88,14.06,10.69
92,93.0,Юнусов 93,1.03,33.333333,10.0,6.0,65.0,8.9,467.94,0.256000,...,25.13,19.71,35.98,11.39,7.79,12.14,16.93,23.38,27.55,19.10
93,NaN,Янова 57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.29,23.20,39.38,10.79,7.34,NaN,NaN,NaN,NaN,NaN
94,94.0,Янова 94,1.03,35.897436,NaN,NaN,NaN,NaN,NaN,NaN,...,15.70,26.81,36.40,14.52,6.58,11.65,18.14,26.30,22.31,21.60
95,95.0,Янова 95,1.53,33.333333,5.2,8.0,41.5,8.9,373.44,0.297000,...,18.20,21.98,33.04,15.82,10.96,NaN,NaN,NaN,NaN,NaN

In [11]:
df_finaly = df_finaly.drop(93,axis=0)

In [12]:
df_finaly = df_finaly.drop("№",axis=1)

In [13]:
df_finaly = df_finaly.drop("Стадия",axis=1)

In [14]:
df_finaly.loc[95,"Пол"] = "ж"

In [15]:
# @title
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from category_encoders import TargetEncoder
from category_encoders import LeaveOneOutEncoder
class coding_methods():
    def __init__(self,df):
        self.df = df
    def OneHot_Encoding(self,column,handle_unknown = "error",drop = None,sparse = True,dtype = float):
        #каждую категорию превращаем в отдельную колонку с 0/1.
        ohe = OneHotEncoder(
        handle_unknown=handle_unknown,
        drop=drop,
        sparse_output=sparse,
        dtype=dtype
        )

        # Параметры, которые важны:
        # handle_unknown
        # Что делать, если при предсказании встречается новая категория.
        # — 'error': выбросит ошибку.
        # — 'ignore': создаст строку из нулей для незнакомого значения.
        # drop
        # Можно удалить одну категорию как базовую (drop='first'), чтобы уменьшить коллинеарность для линейных моделей.
        # sparse
        # True — возвращает разреженную матрицу, экономит память. False — numpy-массив.
        # dtype
        # Тип данных для выходных признаков.
        # OHE хорошо подходит деревьям и линейным моделям, но раздувает размерность, если категорий много.
        encoded = ohe.fit_transform(self.df[[column]])
        new_cols = ohe.get_feature_names_out([column])
        df_encoded = pd.DataFrame(encoded.toarray(), columns=new_cols)
        self.df = pd.concat([self.df.drop(columns=[column]), df_encoded], axis=1)
        return self.df

    def Ordinal_Encoding(self,column):
        #категория превращается в число 0, 1, 2, 3, …
        #Но модель может подумать, что между значениями есть расстояние, которое на самом деле отсутствует.
        enc = OrdinalEncoder(
        handle_unknown='error',
        unknown_value=None,
        encoded_missing_value=-1
        )
        # Параметры:

        # handle_unknown
        # Если встретится категория, которой не было при fit.
        # — 'error'
        # — 'use_encoded_value' (и тогда задаётся unknown_value).

        # unknown_value
        # Значение, в которое будут кодироваться неизвестные категории.

        # encoded_missing_value
        # Чем кодировать пропуски.

        # подходит деревьям решений, которые не реагируют на «порядок» категорий
        encoded = enc.fit_transform(self.df[[column]])
        encoded_data_shifted = encoded + 1
        self.df[column] = encoded_data_shifted
        return self.df
    def Target_Encoding(self,categorical_column,y_column):
        # Каждая категория заменяется средним значением целевой переменной для этой категории.
        # Категория сама как бы «предсказывает», насколько она близка к классу.

        # - Для классификации: p = mean(y).
        # - Для регрессии: тоже mean(y) по категории.

        # Часто используется библиотека category_encoders:
        enc = TargetEncoder(
        smoothing=1.0,
        min_samples_leaf=1
        )
        #Параметры:

        # - smoothing
        # Смягчение эффекта малых категорий: смесь глобального среднего и среднего в категории.
        # Большая smoothing ближе к глобальному mean.

        # - min_samples_leaf
        # Если в категории мало примеров, затираем статистику.

        # Target encoding чувствителен к утечкам, поэтому часто используют кросс-валидационную схему при обучении.
        self.df[categorical_column] = enc.fit_transform(self.df[categorical_column], self.df[y_column])
        return self.df
    def Frequency_or_Count_Encoding(self,column):
        # Кодируем категорию частотой (отношением числа строк класса) или простым количеством.
        # Модель получает информацию о «популярности» значения.
        self.df[column] = self.df[column].map(self.df[column].value_counts())
        return self.df
    # def Leave_One_Out_Encoding(self,column,sigma = 0.1):
    #     enc = LeaveOneOutEncoder(
    #         sigma=sigma
    #     )

    #     self.df[column] = enc.fit_transform(self.df[column])
    #     return self.df

a = coding_methods(df_finaly)
# z = coding_methods()

In [16]:
df_finaly = a.Ordinal_Encoding("Форма")
df_finaly = a.Ordinal_Encoding("Пол")

In [17]:
df_finaly

,ФИО,ПОЛ в плазме,ПОЛ в мембр. Эритроцитов,Лактат,Глюкоза,Общий белок,Мочевина,Кортизол,Зонулин,Холестерин,...,ЭХ_x,ТГ_y,НеЖК,ХЛ,ФЛ_y,ФЛ,СХ_y,СЖК,ТГ,ЭХ_y
0,1,3.08,33.333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.92,16.94,27.66,15.87,24.61,11.10,17.51,27.65,22.61,21.14
1,Азиатцева 2,2.05,28.205128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.57,15.78,20.72,12.09,34.84,14.74,16.96,21.82,25.22,21.26
2,Азиатцева 3,1.03,23.076923,8.0,8.7,65.0,7.7,369.00,0.283000,3.0,...,22.08,21.59,19.26,14.86,22.21,8.67,13.46,19.59,33.53,24.76
3,Андриянова 4,1.53,38.461538,6.8,6.0,85.6,7.7,328.90,0.370714,3.0,...,19.31,24.98,34.26,7.48,13.97,15.56,19.88,29.38,28.71,24.36
4,Андриянова 5,2.05,30.769231,6.8,6.0,85.6,7.7,328.90,0.370714,3.0,...,20.15,19.35,32.04,16.17,12.29,8.10,19.40,15.90,30.89,25.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,Щербаков 91,1.53,25.641026,9.6,9.3,75.2,10.9,222.42,0.342000,3.8,...,15.70,26.81,36.40,14.52,6.57,11.38,15.27,23.91,19.65,29.79
91,Юнусов 92,1.53,33.333333,10.0,6.0,65.0,8.9,467.94,0.256000,7.3,...,19.63,24.78,29.94,11.44,14.21,20.27,32.10,22.88,14.06,10.69
92,Юнусов 93,1.03,33.333333,10.0,6.0,65.0,8.9,467.94,0.256000,7.3,...,25.13,19.71,35.98,11.39,7.79,12.14,16.93,23.38,27.55,19.10
94,Янова 94,1.03,35.897436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.70,26.81,36.40,14.52,6.58,11.65,18.14,26.30,22.31,21.60
95,Янова 95,1.53,33.333333,5.2,8.0,41.5,8.9,373.44,0.297000,2.6,...,18.20,21.98,33.04,15.82,10.96,NaN,NaN,NaN,NaN,NaN

In [18]:
df_finaly

,ФИО,ПОЛ в плазме,ПОЛ в мембр. Эритроцитов,Лактат,Глюкоза,Общий белок,Мочевина,Кортизол,Зонулин,Холестерин,...,ЭХ_x,ТГ_y,НеЖК,ХЛ,ФЛ_y,ФЛ,СХ_y,СЖК,ТГ,ЭХ_y
0,1,3.08,33.333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.92,16.94,27.66,15.87,24.61,11.10,17.51,27.65,22.61,21.14
1,Азиатцева 2,2.05,28.205128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.57,15.78,20.72,12.09,34.84,14.74,16.96,21.82,25.22,21.26
2,Азиатцева 3,1.03,23.076923,8.0,8.7,65.0,7.7,369.00,0.283000,3.0,...,22.08,21.59,19.26,14.86,22.21,8.67,13.46,19.59,33.53,24.76
3,Андриянова 4,1.53,38.461538,6.8,6.0,85.6,7.7,328.90,0.370714,3.0,...,19.31,24.98,34.26,7.48,13.97,15.56,19.88,29.38,28.71,24.36
4,Андриянова 5,2.05,30.769231,6.8,6.0,85.6,7.7,328.90,0.370714,3.0,...,20.15,19.35,32.04,16.17,12.29,8.10,19.40,15.90,30.89,25.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,Щербаков 91,1.53,25.641026,9.6,9.3,75.2,10.9,222.42,0.342000,3.8,...,15.70,26.81,36.40,14.52,6.57,11.38,15.27,23.91,19.65,29.79
91,Юнусов 92,1.53,33.333333,10.0,6.0,65.0,8.9,467.94,0.256000,7.3,...,19.63,24.78,29.94,11.44,14.21,20.27,32.10,22.88,14.06,10.69
92,Юнусов 93,1.03,33.333333,10.0,6.0,65.0,8.9,467.94,0.256000,7.3,...,25.13,19.71,35.98,11.39,7.79,12.14,16.93,23.38,27.55,19.10
94,Янова 94,1.03,35.897436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.70,26.81,36.40,14.52,6.58,11.65,18.14,26.30,22.31,21.60
95,Янова 95,1.53,33.333333,5.2,8.0,41.5,8.9,373.44,0.297000,2.6,...,18.20,21.98,33.04,15.82,10.96,NaN,NaN,NaN,NaN,NaN

In [19]:
df_finaly.info()

<class 'pandas.core.frame.DataFrame'>
Index: 95 entries, 0 to 95
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ФИО                       95 non-null     object
 1   ПОЛ в плазме              95 non-null     float64
 2   ПОЛ в мембр. Эритроцитов  95 non-null     float64
 3   Лактат                    84 non-null     float64
 4   Глюкоза                   84 non-null     float64
 5   Общий белок               84 non-null     float64
 6   Мочевина                  84 non-null     float64
 7   Кортизол                  84 non-null     float64
 8   Зонулин                   84 non-null     float64
 9   Холестерин                84 non-null     float64
 10  здоров(1)\болен(0)        95 non-null     float64
 11  ЭХС                       84 non-null     float64
 12  ТГ_x                      84 non-null     float64
 13  НЭЖК                      84 non-null     float64
 14  СХ_x                      84 non-null     float64
 15  ФЛ_x                      84 non-null     float64
 16  Пол                       95 non-null     float64
 17  Возраст                   63 non-null     float64
 18  Форма                     95 non-null     float64
 19  ЭХ_x                      84 non-null     float64
 20  ТГ_y                      84 non-null     float64
 21  НеЖК                      84 non-null     float64
 22  ХЛ                        84 non-null     float64
 23  ФЛ_y                      84 non-null     float64
 24  ФЛ                        68 non-null     float64
 25  СХ_y                      68 non-null     float64
 26  СЖК                       68 non-null     float64
 27  ТГ                        68 non-null     float64
 28  ЭХ_y                      68 non-null     float64
dtypes: float64(28), object(1)
memory usage: 24.3+ KB

In [20]:
df = df_finaly.drop("ФИО", axis = 1)

In [21]:
df

,ПОЛ в плазме,ПОЛ в мембр. Эритроцитов,Лактат,Глюкоза,Общий белок,Мочевина,Кортизол,Зонулин,Холестерин,здоров(1)\болен(0),...,ЭХ_x,ТГ_y,НеЖК,ХЛ,ФЛ_y,ФЛ,СХ_y,СЖК,ТГ,ЭХ_y
0,3.08,33.333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,14.92,16.94,27.66,15.87,24.61,11.10,17.51,27.65,22.61,21.14
1,2.05,28.205128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,16.57,15.78,20.72,12.09,34.84,14.74,16.96,21.82,25.22,21.26
2,1.03,23.076923,8.0,8.7,65.0,7.7,369.00,0.283000,3.0,0.0,...,22.08,21.59,19.26,14.86,22.21,8.67,13.46,19.59,33.53,24.76
3,1.53,38.461538,6.8,6.0,85.6,7.7,328.90,0.370714,3.0,0.0,...,19.31,24.98,34.26,7.48,13.97,15.56,19.88,29.38,28.71,24.36
4,2.05,30.769231,6.8,6.0,85.6,7.7,328.90,0.370714,3.0,0.0,...,20.15,19.35,32.04,16.17,12.29,8.10,19.40,15.90,30.89,25.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,1.53,25.641026,9.6,9.3,75.2,10.9,222.42,0.342000,3.8,0.0,...,15.70,26.81,36.40,14.52,6.57,11.38,15.27,23.91,19.65,29.79
91,1.53,33.333333,10.0,6.0,65.0,8.9,467.94,0.256000,7.3,0.0,...,19.63,24.78,29.94,11.44,14.21,20.27,32.10,22.88,14.06,10.69
92,1.03,33.333333,10.0,6.0,65.0,8.9,467.94,0.256000,7.3,0.0,...,25.13,19.71,35.98,11.39,7.79,12.14,16.93,23.38,27.55,19.10
94,1.03,35.897436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,15.70,26.81,36.40,14.52,6.58,11.65,18.14,26.30,22.31,21.60
95,1.53,33.333333,5.2,8.0,41.5,8.9,373.44,0.297000,2.6,0.0,...,18.20,21.98,33.04,15.82,10.96,NaN,NaN,NaN,NaN,NaN

In [22]:
x = df.drop("здоров(1)\болен(0)",axis=1)
y = df["здоров(1)\болен(0)"]

In [23]:
x

,ПОЛ в плазме,ПОЛ в мембр. Эритроцитов,Лактат,Глюкоза,Общий белок,Мочевина,Кортизол,Зонулин,Холестерин,ЭХС,...,ЭХ_x,ТГ_y,НеЖК,ХЛ,ФЛ_y,ФЛ,СХ_y,СЖК,ТГ,ЭХ_y
0,3.08,33.333333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,...,14.92,16.94,27.66,15.87,24.61,11.10,17.51,27.65,22.61,21.14
1,2.05,28.205128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,...,16.57,15.78,20.72,12.09,34.84,14.74,16.96,21.82,25.22,21.26
2,1.03,23.076923,8.0,8.7,65.0,7.7,369.00,0.283000,3.0,15.0,...,22.08,21.59,19.26,14.86,22.21,8.67,13.46,19.59,33.53,24.76
3,1.53,38.461538,6.8,6.0,85.6,7.7,328.90,0.370714,3.0,15.0,...,19.31,24.98,34.26,7.48,13.97,15.56,19.88,29.38,28.71,24.36
4,2.05,30.769231,6.8,6.0,85.6,7.7,328.90,0.370714,3.0,16.0,...,20.15,19.35,32.04,16.17,12.29,8.10,19.40,15.90,30.89,25.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,1.53,25.641026,9.6,9.3,75.2,10.9,222.42,0.342000,3.8,NaN,...,15.70,26.81,36.40,14.52,6.57,11.38,15.27,23.91,19.65,29.79
91,1.53,33.333333,10.0,6.0,65.0,8.9,467.94,0.256000,7.3,NaN,...,19.63,24.78,29.94,11.44,14.21,20.27,32.10,22.88,14.06,10.69
92,1.03,33.333333,10.0,6.0,65.0,8.9,467.94,0.256000,7.3,NaN,...,25.13,19.71,35.98,11.39,7.79,12.14,16.93,23.38,27.55,19.10
94,1.03,35.897436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.70,26.81,36.40,14.52,6.58,11.65,18.14,26.30,22.31,21.60
95,1.53,33.333333,5.2,8.0,41.5,8.9,373.44,0.297000,2.6,NaN,...,18.20,21.98,33.04,15.82,10.96,NaN,NaN,NaN,NaN,NaN

In [29]:
mean_df = df.fillna(df.mean(), inplace=False)

In [ ]:
mean_df

In [24]:
mean_x = x.fillna(x.mean(), inplace=False)
mean_y = y.fillna(y.mean(), inplace=False)

In [25]:
mean_x

,ПОЛ в плазме,ПОЛ в мембр. Эритроцитов,Лактат,Глюкоза,Общий белок,Мочевина,Кортизол,Зонулин,Холестерин,ЭХС,...,ЭХ_x,ТГ_y,НеЖК,ХЛ,ФЛ_y,ФЛ,СХ_y,СЖК,ТГ,ЭХ_y
0,3.08,33.333333,29.622619,6.827381,39.155,7.063651,248.718361,95.402933,2.504494,19.000000,...,14.92,16.94,27.66,15.87,24.61,11.100000,17.510000,27.650000,22.610000,21.140000
1,2.05,28.205128,29.622619,6.827381,39.155,7.063651,248.718361,95.402933,2.504494,19.000000,...,16.57,15.78,20.72,12.09,34.84,14.740000,16.960000,21.820000,25.220000,21.260000
2,1.03,23.076923,8.000000,8.700000,65.000,7.700000,369.000000,0.283000,3.000000,15.000000,...,22.08,21.59,19.26,14.86,22.21,8.670000,13.460000,19.590000,33.530000,24.760000
3,1.53,38.461538,6.800000,6.000000,85.600,7.700000,328.900000,0.370714,3.000000,15.000000,...,19.31,24.98,34.26,7.48,13.97,15.560000,19.880000,29.380000,28.710000,24.360000
4,2.05,30.769231,6.800000,6.000000,85.600,7.700000,328.900000,0.370714,3.000000,16.000000,...,20.15,19.35,32.04,16.17,12.29,8.100000,19.400000,15.900000,30.890000,25.730000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,1.53,25.641026,9.600000,9.300000,75.200,10.900000,222.420000,0.342000,3.800000,17.488095,...,15.70,26.81,36.40,14.52,6.57,11.380000,15.270000,23.910000,19.650000,29.790000
91,1.53,33.333333,10.000000,6.000000,65.000,8.900000,467.940000,0.256000,7.300000,17.488095,...,19.63,24.78,29.94,11.44,14.21,20.270000,32.100000,22.880000,14.060000,10.690000
92,1.03,33.333333,10.000000,6.000000,65.000,8.900000,467.940000,0.256000,7.300000,17.488095,...,25.13,19.71,35.98,11.39,7.79,12.140000,16.930000,23.380000,27.550000,19.100000
94,1.03,35.897436,29.622619,6.827381,39.155,7.063651,248.718361,95.402933,2.504494,17.488095,...,15.70,26.81,36.40,14.52,6.58,11.650000,18.140000,26.300000,22.310000,21.600000
95,1.53,33.333333,5.200000,8.000000,41.500,8.900000,373.440000,0.297000,2.600000,17.488095,...,18.20,21.98,33.04,15.82,10.96,11.925735,19.081912,22.808235,24.416029,24.114265

In [26]:
mean_y

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
     ...
90    0.0
91    0.0
92    0.0
94    0.0
95    0.0
Name: здоров(1)\болен(0), Length: 95, dtype: float64

In [27]:
mean_y.to_csv("mean_y", index = False)
mean_x.to_csv("mean_x", index = False)

In [28]:
mean_df.to_excel("mean_df.xlsx", index = False)

NameError: name 'mean_df' is not defined